/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jessie' at '2/9/18 3:32 PM' with Gradle 2.14.1
 *
 * @author jessie, @date 2/9/18 3:32 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
